### ISSUE TITLE
Thoughts on homework and curriculums

### ISSUE THREAD

**Issue by mitio** [rubymonsters/coaching#3]
I've read this coaching guide and must say it is very, very useful. I've been runnung a local study group here since March 2014 inspired exactly by @rubymonsters and thank you @svenfuchs!

I have some thoughts I'd like to share and discuss with you and I'll use issues for these.
### No homework and no fixed curriculum
1. I don't give any homework assignments, much less any required ones. I make that explicitly clear.
2. I avoid a common curriculum.

I did this for almost a year now and have some new observations and conclusions, which I will share at the end of this expose, but first I will share my initial thoughts.

From my own experience and judging by the experience of others, I find two major reasons why people would stop coming to such regular sessions:
1. They don't find the time or motivation to do the homework and when the time comes for the next meeting, their consciousness is telling them, "You did not prepare! Shame on you! You cannot go now, or if you go, you will have to bear that shame!"  They also feel behind everybody else. And they skip a meeting, probably telling themselves, "I will do my homework next time, I will catch up and will go to the next one." But we all know it's only downhill from here :) Things start to pile up and that feeling of lagging behind and not catching up is just ever increasing. That is why I decided to be explicit about not giving any homework.
2. People have a more important engagement and they miss a meeting or two. Then they start feeling that they've missed too much and are probably way behind others. This would happen even if there are no homework assignments. The only requirement is something like a curriculum. If they know there is a curriculum and everybody's following it, when they miss a meeting or two—that's it. They stop coming in.

So, my first attempt to the study groups was more ad-hoc and without a carefully planned agenda. No specific curriculum. No common curriculum. Just a vision where we should probably get after some time. However, I try to determine each participant's motivation and to see what would be an appropriate end goal for each of them. And I try to help them stay motivated and move towards their own goals.

I wanted to achieve a group where it would be completely okay to come by and have fun or do something different for 2-3 hours a week, even if you've missed a couple. I find 2 hours a week a lot more than zero hours a week.

That is why I decided to not give homework and have no curriculum. To avoid the two reasons I identified for why people quit new things. I wanted to give people enough time with this new adventure to have a higher chance of hooking them up. I tried to prevent the feeling of "I've missed too much".

One might say, "Well, if they don't do their homework, they're not motivated enough. If they're not motivated enough, it is not going to work."

I think it is a bit more complex than that.

I imagine being in a study group, but having other egnagements going on—for example school, work, other side projects or hobby activities. I suddenly find this new thing, coding. Programming. Some cool people are trying to teach me and they seem pretty friednly and open about it. Excited even. I find it nice, but it's also hard. It requires focus and a lot of thinking. It's not something I can just do absendmindedly. It is completely new for me, it has tons of new words in it. It almost feels like that first time when I stepped into a car with manual transmission and tried to drive it—so much moving parts, so many new things to think about. Almost frustrating at the beginning. And it takes more than a few hours or a few days to start getting the hang of it. But when you do—this is when the fun starts! You'd be very glad you stayed, that you persisted.

I want to give the participants their chance to do that. To let them know that these weekly meetups are a safe place where they can come and in a like-minded group explore very new things, get help, get guidance, escape from the usual daily stuff. To make it a pleasurable and awaited experience, not yet another dreaded engagement you have to worry about and prepare for.

I try to come up with a suitable plan for each of the participants individually and it's more or less working for now. There are still a lot of things to improve, of course, but I think it was not bad.
### On progress

Sven mentions letting participants know they're making progress. I completely agree with all he's written in the guide, with just one minor note. It's also possible that I've misinterpreted what he said in the guide, but still—I think there definitely should be a goal for each participant. Maybe not a common goal, but a goal. However, I'd avoid a detailed curriculum.

I had some sessions in the beginning where I'd be explaining some technical concepts for a long time. Something like a curriculum, but it was not a fixed one, we did not know what exactly to talk about in the next meeting or how many there were _before the end_. I tried to avoid that.

The reason for that being if I show them how much stuff is left, it might be too daunting and crushing. I want them to see that they're making progress, without letting them know exactly how much is left out there. Moreover, even I am not sure what path each one of them is going to take on and if the goal will not change at some point.

So, end goal—yes. Constant reminder what an amazing job they've don and are doing—yes! Showing them how vast the field is and how much they will probably have to learn—no. Not at first, at least.
### Evolution

Based on my experience until now, I'd say that I want to keep these principles, especially the individual approach and individual goals. I'd now give two options for each participant:
1. Casually attend the meetings, go at your own pace, forget homework assignments and curriculums. We'll help you find your goal, coach you, guide you. We'll have fun exploring this new world together. You'll probably also find other companions there.
2. You know what you want. You want to be a developer and you are very, very determined to do it. You seek any help you can get. You pour all of your time and energy you can spare into that. Awesome! We'll be there for you and will catalyze your efforts. Together, we'll help you build a jetspeed of entering this new field. We'll give you homeworks, books, things to read, tools to solve your problems, will give you new challenges, etc. We'll keep you busy.

Sorry for the looong post. I'm interested to see what you think about what I've shared.

**Comment by svenfuchs** [comment]
@mitio Thanks a ton for taking the time to share your thoughts! This is super interesting to us. 

ALSO, it is just amazing to hear that the Ruby Monsters have inspired you to found a study group. That's pretty awesome, really.

You raise a lot of good points. Everything you say makes sense to me. I think there are lots of different styles to run a group like this. Every group is different, and coaches are different ...

We've also started out with an ad-hoc approach of coming up with topics and exercises every week. We found that we were way to chaotic doing so, but of course that doesn't mean everyone else will be as bad as we were :) When we discussed this with some of the original members of the group they didn't even agree with this perception. 

However, after running 2 groups like this we noticed that sticking a certain order of topics is valuable in order to reduce confusion and overload. So in the last 2 groups (we've run 4 beginners groups over time) we've tried to stick to that order, and optimize it (the result is that book, with a few additions that still need to be ordered in a different way). 

Also, we found that giving people a book to read at home, which has a similar order of topics (we used "Learning to program") is beneficial. Even if some students don't have enough time to read a lot, reading just a few pages is the most low barrier for many. This helps their brain stay active on the topic even if they don't do a lot. Also, some students would actually read a lot (one of them has read the entire book in 2 weeks, doing a lot of the exercises). That's great because now there are some who are more confident asking more questions, and giving answers to others: in a way they start coaching each other more. 

In the beginning of each meeting we ask who did what re learning programming. Some don't do anything, some do quite a bit. Whatever they say, it's super ok. We also explain in the very first meeting that it's completely up to them to decide how much time they want to invest. And no one ever is criticized for not doing homework, obviously. 

So, it sounds to me that we seem to run our groups in similar ways with regards to the expectations that are raised, and the fact that participating casually, and only spending time for learning at the group meetings is completely ok, too. 

I guess the conclusion is that no-one should feel rejected, everyone should feel included all the time, no matter how much time they can/want/do spend during the week. On the other hand I also think it makes sense to encourage them to try and do it. So, even if you don't call it "homework" I think it is good for them to have opportunities to pick things up when they want to, and learn at a faster pace. In our first groups people just signed up for codeschool and similar tutorials, or bought random books on Amazon. While that's awesome, I also think there's a benefit when there's at least one shared resource.

Also, on the topic of a shared curriculum, I think there's quite some overlap in what you say about goals and our approach. In the beginners group (which takes about 3-6 months) we focus on learning all the Ruby basics that you need to build your own Sinatra or Rails apps. That's pretty limited knowledge, actually, and we try to get to this point as quickly as possible because we've made the experience that this is very motivating to students: they can now call themselves "developers". In order to get there it seems beneficial to have this one shared goal for the group. Not only do they know what's on the "agenda", they also start supporting each other more. Now, this goal can be devided into smaller goals (e.g. our first milestone is to learn and discuss things like methods and objects, the second milestone is to get the `MailboxTextFormatter` exercise finished, and from then on it's just a few steps to the first web app that serves a static HTML file). We found that knowing this next smaller goal also is pretty motivating to some. They keep asking questions like "How far did we get?" or "After this, what comes next?".

Btw, I am just noticing that maybe there's a misunderstanding, too. We have called our book "Ruby for beginners" our "curriculum". That's kinda true, but not quite. We do plan to hand this book out to the next beginners group, but otoh we totally also adapt to the group spontaneously every week, and sometimes just change the order of topics if someone asks a specific question etc. So the book is just a rough order of topics. In the meetings we don't cover all of it, and we don't do it in this exact order.

Of course you are right that as soon as some people spend more time on learning than others than the group will kinda split up in different levels of understanding and skills fairly quickly. 

On the one hand this seems pretty natural anyway. Some people have an easier time picking up these topics than others. Others are super disciplined and just keep on learning every day. Others don't do anything except attending the group and picking things up as they go. All of this is super ok to everyone ... although, of course, we need to re-inforce that ok-ness by stating it, in order to overcome the anxiety that you mentioned before. 

On the other hand we've actually found this beneficial, too. It eventually contributes to the feeling of being accepted and included no matter what achievements you make: it's about fun, and doing things at your own pace and in your own ways. People who are, after a few weeks, more advanced will start helping others, ... which again helps them deepen their understanding themselves, and makes them feel proud that they've been able to explain concepts. So everyone wins.

All this said ... i think there are a million factors that contribute to how a group eventually grows and develops. So there can't ever be one true style of running a group.

I'll think about your points more, and probably adapt some of it for our book. Like, maybe we should be more verbose regarding what expectations we have about homework in our preface (As in, "Doing zero homework is just fine, too." etc)

Please say hi from me to your group :)

**Comment by mitio** [comment]
Sven, thanks again for expanding on your thoughts. It adds nicely to the guide and I now have a fuller picture and better understanding of what happens in your groups. It seems it is not very different than what we do, after all, as you also point out. Still, you've given me some more food for thought. We'll improve. :)

The book! I completely forgot about it!

I'm really excited that it's there and I'd really like to try it. I'll read it and probably start using it. I agree about the shared resource, a common goal and rough milestones. It's also very nice to let the participants know that we can change the order of topics on how they like it. A huge thank you to you personally and to whoever also contributed to it for making it happen!

I will share how it goes. I also have a bunch of other stuff I'd be curious to share and discuss at some point and see what comes of it. Maybe even talk to you and to other coaches in person some day. I think that it would be beneficial for all of us.

:heart:

**Comment by thatbettina** [comment]
I know that you closed the issue, but I just wanted to say it's soooo cool
that this conversation happened.

On Thu, Jan 15, 2015 at 12:00 AM, Dimitar Dimitrov <notifications@github.com

> wrote:
> 
> Closed #3 https://github.com/rubymonsters/coaching/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rubymonsters/coaching/issues/3#event-219098929.

## 

Bettina Shzu-Juraschek
Fuldastraße 19-20
12045 Berlin

+49 (0)163 164 7045
bettina.shzu@gmail.com

**Comment by svenfuchs** [comment]
@mitio Likewise. Thanks for sharing your thoughts! Should you ever come to Berlin make sure to ping us, so we can discuss things in person.

@thatbettina \o/

:heart:
